### PR TITLE
Remove properies that should come in KorMA

### PR DESCRIPTION
**Pull request by SerVB**
This change should come with korlibs/korge-next#109.

### CODE REVIEW

**Comment by soywiz** [comment]
Next steps:
* Grab the hash id master is pointing to
* Update the project to point to that hash and compute the content SHA-256
* Make a PR updating this file: https://github.com/korlibs/awesome.korge.org/blob/master/_bundles/korlibs-bundle-source-extensions.md

**Comment by SerVB** [comment]
@soywiz , it's strange: I don't have errors nor warnings when I specify incorrect hash or don't specify it at all. Do you have any ideas why can it happen and how can I fix it? `korgePluginVersion=2.0.0.2`

image

**Comment by soywiz** [comment]
I think that's a bug of the plugin. It was a quick and dirty 1-day implementation and I plan to fix that. You have to remove the `bundles` folder (that probably won't be there in future versions) and maybe the `build/korge-bundles` folder, and then retry.

**Comment by soywiz** [comment]
The user experience for this is really bad right now. But at least works somehow.
You can also provide the repo and then use `master` instead of a tag. But then it stops being secure and the artifact you agreed to use might not be the same if the author changes it.

**Comment by SerVB** [comment]
@soywiz 

> You have to remove the bundles folder (that probably won't be there in future versions) and maybe the build/korge-bundles folder, and then retry.

I've deleted only bundles folder before my experiments and hashes have not been checked.

Thank you, after I've deleted build/korge-bundles, I now see messages about hashes!

**Comment by soywiz** [comment]
Just created this repo: https://github.com/korlibs/kotlin-source-dependency-gradle-plugin

Going to try to publish a separate plugin for this today (and will include it in korge) until there is an official solution for sharing code.

**Pull request merged**
